### ISSUE TITLE
Unexpected type (undefined) for parameter PlatformID

### ISSUE THREAD

**Issue by EdwinKuo1337** [ECPay/ECPayAIO_Node.js#14]
```
Unexpected error format in Credit Card Payment Result Lambda function: Error: Unexpected type (undefined) for parameter PlatformID.
    at /var/task/node_modules/ecpay_aio_nodejs/lib/ecpay_payment/verification.js:276:26
    at Array.forEach (<anonymous>)
    at QueryParamVerify.verify_param_by_pattern (/var/task/node_modules/ecpay_aio_nodejs/lib/ecpay_payment/verification.js:204:29)
    at QueryParamVerify.verify_query_param (/var/task/node_modules/ecpay_aio_nodejs/lib/ecpay_payment/verification.js:518:18)
    at ECpayQueryClient._query_pos_proc (/var/task/node_modules/ecpay_aio_nodejs/lib/ecpay_payment/query_client.js:85:26)
    at ECpayQueryClient.query_credit_period (/var/task/node_modules/ecpay_aio_nodejs/lib/ecpay_payment/query_client.js:30:24)
    at Runtime.handler (/var/task/index.js:215:45)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)
```

在使用`query_credit_period`的時候提供`MerchantTradeNo`, 並且有設定好測試帳號的config:

```
const options = {
  "OperationMode": "Test", //Test or Production
  "MercProfile": {
    "MerchantID": "3002607",
    "HashKey": "pwFHCqoQZGmho4w6",
    "HashIV": "EkRm7iFT261dpevs"
  },
  "IgnorePayment": [
//    "Credit",
   "WebATM",
   "ATM",
   "CVS",
   "BARCODE",
   "AndroidPay"
  ],
  "IsProjectContractor": false
}

module.exports = options
```

呼叫`query_trade_info`就沒有這個錯誤，看了code以後發現是`lib/ecpay_payment/ECPayPayment.xml`當中的`<QueryTradeInfo>`裡面有這個parameter:
```
<param  type="String"  require="0" name="PlatformID">
  <pattern>^(\d{7,10}|)$</pattern>
</param>
```

但是`<QueryCreditCardPeriodInfo>`卻少了這個param，我自己加上以後測試就能解決問題，正確query_credit_period

**Comment by AllennChang** [comment]
感謝您提供的解決方式, 已依建議加上參數,
