### ISSUE TITLE
範例程式Donation出錯

### ISSUE THREAD

**Issue by housemeow** [ECPay/ECPayAIO_Node.js#7]
使用範例程式得到以下錯誤，想請問該如何解決：

```json
{
  "errorType": "Error",
  "errorMessage": "Unexpected option of param Donation (2). Available option: (0,1).",
  "trace": [
    "Error: Unexpected option of param Donation (2). Available option: (0,1).",
    "    at /opt/nodejs/node_modules/ecpay_payment_nodejs/lib/ecpay_payment/verification.js:222:30",
    "    at Array.forEach (<anonymous>)",
    "    at AioCheckOutParamVerify.verify_param_by_pattern (/opt/nodejs/node_modules/ecpay_payment_nodejs/lib/ecpay_payment/verification.js:204:29)",
    "    at AioCheckOutParamVerify.verify_aio_inv_param (/opt/nodejs/node_modules/ecpay_payment_nodejs/lib/ecpay_payment/verification.js:492:18)",
    "    at ECpayPaymentClient._aiochkout_base_proc (/opt/nodejs/node_modules/ecpay_payment_nodejs/lib/ecpay_payment/payment_client.js:177:39)",
    "    at ECpayPaymentClient.aio_check_out_all (/opt/nodejs/node_modules/ecpay_payment_nodejs/lib/ecpay_payment/payment_client.js:21:14)",
    "    at Runtime.exports.handler (/var/task/checkoutCart.js:60:37)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

**Comment by AllennChang** [comment]
您好
錯誤訊息得知:送出Donation參數值為2，
而參數Donation僅支援0或1，
金流API相關參數設定可參考金流API文件(https://www.ecpay.com.tw/Content/files/ecpay_011.pdf) 

若還有任何使用問題, 歡迎再跟我們反應, 感謝您
